name: 01_01_02_24_hello_world

on:
  push:
    branches:
      - main

env:
  TASK_FOLDER: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Pull selenoid images
        run: |
          docker pull selenoid/vnc_chrome:128.0
          docker pull selenoid/video-recorder:latest-release

      - name: Run selenoid in Docker container
        env:
          OVERRIDE_VIDEO_OUTPUT_DIR: ${{ github.workspace }}/video
        run: |
          mkdir -p video logs
          docker compose -f docker-compose.yml up -d

      - name: Wait selenoid status
        run: |
          timeout 60 bash -c 'until curl -fsS http://127.0.0.1:4444/status; do sleep 2; done'
          echo "Selenoid is ready!"

      - name: Build with Maven
        run: mvn -B test -Dremote.url=http://127.0.0.1:4444/wd/hub

      - name: Check video directory
        if: always()
        run: |
          echo "Video directory contents:"
          ls -lah ./video || echo "Video directory not found"

      - name: Show Selenoid logs
        if: always()
        run: |
          echo "Selenoid logs:"
          docker compose -f docker-compose.yml logs selenoid --tail 100

      - name: Uploading report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./target/surefire-reports

      - name: Uploading video
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: video
          path: ./video

      - name: Uploading logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./logs

      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.yml down -v